ccflags-y += -I$(srctree)/drivers/misc/mediatek/teei/$(CONFIG_MICROTRUST_TEE_VERSION)/common/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/teei/$(CONFIG_MICROTRUST_TEE_VERSION)/tz_driver/include

obj-y += fpc1022_tee.o