ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/SOLOMOM/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y += atmel_mxt_ts.o
